set(SUITESPARSE_FOUND TRUE)
set(CXSPARSE_FOUND TRUE)

list(APPEND SUITESPARSE_INCLUDE_DIRS
    ${CXSPARSE_INCLUDE_DIR}
    ${AMD_INCLUDE_DIR}
    ${CAMD_INCLUDE_DIR}
    ${COLAMD_INCLUDE_DIR}
    ${CCOLAMD_INCLUDE_DIR}
    ${CHOLMOD_INCLUDE_DIR}
    ${SUITESPARSEQR_INCLUDE_DIR}
    ${SUITESPARSE_CONFIG_INCLUDE_DIR})

list(APPEND CERES_STATIC_SUITESPARSE_LIBRARIES
    "\${_IMPORT_PREFIX}/${SUITESPARSEQR_LIBRARY}"
    "\${_IMPORT_PREFIX}/${CHOLMOD_LIBRARY}"
    "\${_IMPORT_PREFIX}/${CCOLAMD_LIBRARY}"
    "\${_IMPORT_PREFIX}/${CAMD_LIBRARY}"
    "\${_IMPORT_PREFIX}/${COLAMD_LIBRARY}"
    "\${_IMPORT_PREFIX}/${AMD_LIBRARY}")

  foreach (LIB ${LAPACK_LIBRARIES})
    list(APPEND CERES_STATIC_SUITESPARSE_LIBRARIES "\${_IMPORT_PREFIX}/${LIB}")
  endforeach()

  list(APPEND CERES_STATIC_SUITESPARSE_LIBRARIES
    "\${_IMPORT_PREFIX}/${BLAS_LIBRARIES}"
    "\${_IMPORT_PREFIX}/${SUITESPARSE_CONFIG_LIBRARY}"
    "\${_IMPORT_PREFIX}/${METIS_LIBRARY}"
    "\${_IMPORT_PREFIX}/${CXSPARSE_LIBRARY}")

list(APPEND CERES_SHARED_SUITESPARSE_LIBRARIES
    "${CMAKE_BINARY_DIR}/${SUITESPARSEQR_LIBRARY}"
    "${CMAKE_BINARY_DIR}/${CHOLMOD_LIBRARY}"
    "${CMAKE_BINARY_DIR}/${CCOLAMD_LIBRARY}"
    "${CMAKE_BINARY_DIR}/${CAMD_LIBRARY}"
    "${CMAKE_BINARY_DIR}/${COLAMD_LIBRARY}"
    "${CMAKE_BINARY_DIR}/${AMD_LIBRARY}")

foreach (LIB ${LAPACK_LIBRARIES})
  list(APPEND CERES_SHARED_SUITESPARSE_LIBRARIES "${CMAKE_BINARY_DIR}/${LIB}")
endforeach()

list(APPEND CERES_SHARED_SUITESPARSE_LIBRARIES
  "${CMAKE_BINARY_DIR}/${BLAS_LIBRARIES}")

foreach (LIB ${LAPACK_LIBRARIES})
  list(APPEND CERES_SHARED_SUITESPARSE_LIBRARIES "${CMAKE_BINARY_DIR}/${LIB}")
endforeach()

list(APPEND CERES_SHARED_SUITESPARSE_LIBRARIES
  "${CMAKE_BINARY_DIR}/${SUITESPARSE_CONFIG_LIBRARY}"
  "${CMAKE_BINARY_DIR}/${METIS_LIBRARY}"
  "${CMAKE_BINARY_DIR}/${CXSPARSE_LIBRARY}")


set(SUITESPARSE_VERSION_FILE
    ${CMAKE_BINARY_DIR}/${SUITESPARSE_CONFIG_INCLUDE_DIR}/SuiteSparse_config.h)

if (NOT EXISTS ${SUITESPARSE_VERSION_FILE})
    message(
      "Could not find file: ${SUITESPARSE_VERSION_FILE} containing version "
      "information for >= v4 SuiteSparse installs, but SuiteSparse_config was "
      "found (only present in >= v4 installs).")
else (NOT EXISTS ${SUITESPARSE_VERSION_FILE})
	file(READ ${SUITESPARSE_VERSION_FILE} SUITESPARSE_CONFIG_CONTENTS)

	string(REGEX MATCH "#define SUITESPARSE_MAIN_VERSION [0-9]+"
	  SUITESPARSE_MAIN_VERSION "${SUITESPARSE_CONFIG_CONTENTS}")
	string(REGEX REPLACE "#define SUITESPARSE_MAIN_VERSION ([0-9]+)" "\\1"
	  SUITESPARSE_MAIN_VERSION "${SUITESPARSE_MAIN_VERSION}")

	string(REGEX MATCH "#define SUITESPARSE_SUB_VERSION [0-9]+"
	  SUITESPARSE_SUB_VERSION "${SUITESPARSE_CONFIG_CONTENTS}")
	string(REGEX REPLACE "#define SUITESPARSE_SUB_VERSION ([0-9]+)" "\\1"
	  SUITESPARSE_SUB_VERSION "${SUITESPARSE_SUB_VERSION}")

	string(REGEX MATCH "#define SUITESPARSE_SUBSUB_VERSION [0-9]+"
	  SUITESPARSE_SUBSUB_VERSION "${SUITESPARSE_CONFIG_CONTENTS}")
	string(REGEX REPLACE "#define SUITESPARSE_SUBSUB_VERSION ([0-9]+)" "\\1"
	  SUITESPARSE_SUBSUB_VERSION "${SUITESPARSE_SUBSUB_VERSION}")

    # This is on a single line s/t CMake does not interpret it as a list of
    # elements and insert ';' separators which would result in 4.;2.;1 nonsense.
    set(SUITESPARSE_VERSION
      "${SUITESPARSE_MAIN_VERSION}.${SUITESPARSE_SUB_VERSION}.${SUITESPARSE_SUBSUB_VERSION}")
    message("-- SUITESPARSE_VERSION = ${SUITESPARSE_VERSION}")
endif (NOT EXISTS ${SUITESPARSE_VERSION_FILE})

set(CXSPARSE_VERSION_FILE ${CMAKE_BINARY_DIR}/${CXSPARSE_INCLUDE_DIR}/cs.h)

if (NOT EXISTS ${CXSPARSE_VERSION_FILE})
    message(
      "Could not find file: ${CXSPARSE_VERSION_FILE} "
      "containing version information in CXSparse install located at: "
      "${CXSPARSE_INCLUDE_DIR}.")
else (NOT EXISTS ${CXSPARSE_VERSION_FILE})
    file(READ ${CXSPARSE_VERSION_FILE} CXSPARSE_VERSION_FILE_CONTENTS)

    string(REGEX MATCH "#define CS_VER [0-9]+"
      CXSPARSE_MAIN_VERSION "${CXSPARSE_VERSION_FILE_CONTENTS}")
    string(REGEX REPLACE "#define CS_VER ([0-9]+)" "\\1"
      CXSPARSE_MAIN_VERSION "${CXSPARSE_MAIN_VERSION}")

    string(REGEX MATCH "#define CS_SUBVER [0-9]+"
      CXSPARSE_SUB_VERSION "${CXSPARSE_VERSION_FILE_CONTENTS}")
    string(REGEX REPLACE "#define CS_SUBVER ([0-9]+)" "\\1"
      CXSPARSE_SUB_VERSION "${CXSPARSE_SUB_VERSION}")

    string(REGEX MATCH "#define CS_SUBSUB [0-9]+"
      CXSPARSE_SUBSUB_VERSION "${CXSPARSE_VERSION_FILE_CONTENTS}")
    string(REGEX REPLACE "#define CS_SUBSUB ([0-9]+)" "\\1"
      CXSPARSE_SUBSUB_VERSION "${CXSPARSE_SUBSUB_VERSION}")

    # This is on a single line s/t CMake does not interpret it as a list of
    # elements and insert ';' separators which would result in 3.;1.;2 nonsense.
    set(CXSPARSE_VERSION "${CXSPARSE_MAIN_VERSION}.${CXSPARSE_SUB_VERSION}.${CXSPARSE_SUBSUB_VERSION}")
    message("-- CXSPARSE_VERSION = ${CXSPARSE_VERSION}")
endif (NOT EXISTS ${CXSPARSE_VERSION_FILE})
